In [1]:
import wandb
import pandas as pd
# Note that we use save_code=True in the call to wandb.init so the notebook is uploaded and versioned by W&B
run = wandb.init(project="nyc_airbnb", group="eda", save_code=True)
local_path = wandb.use_artifact("sample.csv:latest").file()
df = pd.read_csv(local_path)

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/us-ml-project/.netrc.
wandb: Currently logged in as: shawnkneupper (shawnkneupper-western-governors-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           3 non-null      int64
 1   name         3 non-null      object
 2   price        3 non-null      int64
 3   last_review  3 non-null      object
dtypes: int64(2), object(2)
memory usage: 228.0+ bytes

In [3]:
df.describe()

        id       price
count  3.0    3.000000
mean   2.0  133.333333
std    1.0  104.083300
min    1.0   50.000000
25%    1.5   75.000000
50%    2.0  100.000000
75%    2.5  175.000000
max    3.0  250.000000

In [4]:
df.head()

   id       name  price last_review
0   1  Listing A    100  2023-01-01
1   2  Listing B    250  2023-02-15
2   3  Listing C     50  2023-03-10

In [6]:
# Drop outliers
min_price = 10
max_price = 350
idx = df['price'].between(min_price, max_price)
df = df[idx].copy()
# Convert last_review to datetime
df['last_review'] = pd.to_datetime(df['last_review'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           3 non-null      int64
 1   name         3 non-null      object
 2   price        3 non-null      int64
 3   last_review  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 228.0+ bytes

In [8]:
run.finish()